### ISSUE TITLE
Exclusions?

### ISSUE THREAD

**Issue by tyson** [ck86/gulp-bower-files#1]
This is great, thanks for putting it together. 

I was wondering though, Is there a way to exclude certain components? For example, Bourbon (http://bourbon.io/) doesn't have any .js files as it's just for sass, so using the override won't work (I tried setting the main value to an empty string but it didn't like that either).

**Comment by ck86** [comment]
Thanks for your great feedback. I never used a bower component like this, so there isn't any way to do this yet.

What do you think about to add an option for the overrides section? I would prefer `ignore: true`.

**Comment by tyson** [comment]
That would be great!

**Comment by taai** [comment]
Please, add this to documentation!
This plugin is very useful. Thank you! :smiley:
