### ISSUE TITLE
Filter / Concat ?

### ISSUE THREAD

**Issue by unDemian** [ck86/gulp-bower-files#10]
I'm kinda new to gulp and node.js and I don't understand how to make gulp-bower-files work with gulp-filter or gulp-less. What I'm trying to do is filter only the .less files from the bower components and parse + concat them to a single file.

**Comment by cmosguy** [comment]
demian-  Any luck with this, I am interested as well.

**Comment by ck86** [comment]
This plugin just selects all main bower files, which are typically not the less files. You can import the less files in your own one and let gulp-less compile these file(s).

**Comment by unDemian** [comment]
Yeap, I understood that, that problem is I didn't manage to import the returned bower files in any plugins, for filter, concat or less.

**Comment by ck86** [comment]
You don't need to use my plugin to solve the less problem. If I understood something wrong, you are welcome to explain the problem in more detail. ;)

**Comment by unDemian** [comment]
I know :)
The thing is that your plugin returns a gulp.src object with all the main bower files, which is wonderful. What I'm trying to achieve is to pipe that response to another plugin, firstly I'll want to filter only the less files then process them, same for jade or coffee.

**Comment by ck86** [comment]
You can split this in two tasks, at first you copy all bower files with gulp-bower-files and then you make a common gulp.src call with the files you want.

**Comment by unDemian** [comment]
Uhm.. I guess, isn't there a way to process the bower files without copying them. So that I don't create duplicates. My current scenario is like this: Get all the main files using your plugin, filter only less files process them and concatenate the result into a single .css file. The problem is that the object returned from your plugin cannot be piped to another gulp plugin, the only pipe that worked was with dest, but that copies the files. I tried mapping the result with event-stream, and then I get the actual file object but not sure how to send all the files to the next pipe :)

Sorry for bothering you here, I am sure this is not a problem with your plugin but some misunderstanding on my part regarding how gulp & node pipes work.
Feel free to close this issue

Thanks

**Comment by ck86** [comment]
I will check why plugins like gulp-filter are not working correctly and give you feedback.

**Comment by ck86** [comment]
Hey @unDemian look here: https://gist.github.com/ck86/7e380e2db7c466312d1c

I could successfully copy only the *.scss files from the bootstrap-sass component.
