### ISSUE TITLE
Always need overrides

### ISSUE THREAD

**Issue by CKGrafico** [ck86/gulp-bower-files#15]
I always need to override :S

```
{
    "name": "app",

    "dependencies": {
        "jquery": ">= 1.8.3"
    }
}
```

[gulp] Error in plugin 'gulp-bower-files': The bower package jquery has no main file(s), use the overrides property in your bower.json

---

```
{
    "name": "app",
    "dependencies": {
        "jquery": ">= 1.8.3"
    },

    "overrides": {
        "jquery": {
            "main": "jquery.js"
        }
    }
}
```

**Comment by ck86** [comment]
What jQuery version do you have installed exactly?

**Comment by CKGrafico** [comment]
Last version: jQuery JavaScript Library v2.1.0

**Comment by ck86** [comment]
It seems they removed the main property in their bower.json file. You can open an issue there with this link for recommendation: https://github.com/bower/bower.json-spec#main
