### ISSUE TITLE
Suggestion: Reserver word for ignore dependencies

### ISSUE THREAD

**Issue by CKGrafico** [ck86/gulp-bower-files#16]
When I have a dependency of a bower package like Sizzle for jQuery, if I override jQuery also sizzle files are passing with gulp.

```
{
    "dependencies": {
        "jquery": ">= 1.8.3",
    },

    "overrides": {
        "jquery": {
            "main": "jquery.js"
        }
    }
}
```

this is generated
| js
---| jquery
--------| jquery.js
---| sizzle
--------| sizzle.js

If I write something like

```
{
    "dependencies": {
        "jquery": ">= 1.8.3",
    },

    "overrides": {
        "jquery": {
            "main": "jquery.js"
        },
                "sizzle": {
            "main": "nothing"
        }
    }
}
```

this is generated
| js
---| jquery
--------| jquery.js

YEAH! But Can we use a reserved word for this?
Other better method?

**Comment by ck86** [comment]
You can exclude components by adding `ignore: true` in the `overrides` section, e.g.:

``` javascript
{
    "overrides": {
        "sizzle": {
            ignore: true
        }
    }
}
```
