### ISSUE TITLE
Different to gulp-bower?

### ISSUE THREAD

**Issue by Amparose** [ck86/gulp-bower-files#17]
So... what is the difference between this and [gulp-bower](https://github.com/zont/gulp-bower), asides from your documentation is better?

**Comment by ck86** [comment]
I would say that gulp-bower installs your bower components und creates a gulp.src() stream with all files.

This plugin creates a gulp.src() stream with all main files based on the bower.json file of your previously installed components.
For example if you have installed jquery you will get a gulp.src() stream just with one file (jquery.js) and not all the others files like tests and so on.

**Comment by Amparose** [comment]
Ah that's cool. So how would one configure an override for bootstrap to include the less and js files rather than the /dist css/js etc?

**Comment by ck86** [comment]
not tested:

``` javascript
{
    "overrides": {
        "bootstrap": {
            "main": [
                "./less/**",
                "./js/**"
            ]
        }
    }
}
```

**Comment by Amparose** [comment]
Awesome! Thanks for the help.
