### ISSUE TITLE
Add files without overriding project bower.json files

### ISSUE THREAD

**Issue by nfroidure** [ck86/gulp-bower-files#23]

**Comment by ck86** [comment]
Can you explain what you exactly want to do?

**Comment by nfroidure** [comment]
Sometimes, bower package maintainers just forget to declare one main file to their bower.json.

In this cas, you have to overrides the main file whith the whole list of main files + the forgotten one.

It would be nice to have an option to do partial overrides :

``` js
{
  "overrides": {
    "PACKAGE": {
      "add_main": [
        "./forgottenfile.one",
        "./forgottenfile.two"
      ]
    }
  }
}
```

**Comment by nfroidure** [comment]
Also conditionnal overrides would be cool (setting minified files for the production and normal ones for dev is a use case):

``` js
{
  "overrides": {
    "PACKAGE": {
      "main": {
        "prod": "/file.min.ext",
        "dev": "/file.ext"
      }
    }
  }
}
```

**Comment by ck86** [comment]
1: OK, but what is the problem to copy the main property from the bower component, pasting it to your bower.json and extend the list of files?

2: Is an option, but you can also minify them in your gulp task.

**Comment by nfroidure** [comment]
1: Sometimes it can be a very long list. Also, the list may change, addign just the missing file allows less frequent changes to the projet bower.json file.

2: you're right, but there are many more use cases, some libs could break when minified, some other could   purpose several builds (with debug informations for development purpose).

**Comment by ck86** [comment]
I have implemented the environment based selection, but I think there are too many ways to override the file selection if I would add the `add_main` property.

**Comment by nfroidure** [comment]
No prob. Thanks for the env select!
