### ISSUE TITLE
Files from devDependencies are not being moved

### ISSUE THREAD

**Issue by ivandotv** [ck86/gulp-bower-files#25]
Is it possible to move `devDependencies` ?

**Comment by ck86** [comment]
Move to?

**Comment by ivandotv** [comment]
I mean in the bower file I have `devDependencies`, when I invoke the plugin, it only moves `dependencies`. It doesn't moves files declared in `devDependencies`

**Comment by ck86** [comment]
You can add the option `includeDev: true`, e.g.:

```
bowerFiles({ includeDev: true }).pipe(...)
```

**Comment by ivandotv** [comment]
Thanks, you should document that option.

**Comment by ck86** [comment]
I will update the documentation in 0.2.x branch
