### ISSUE TITLE
Normalize Vinyl files before outputting the Stream

### ISSUE THREAD

**Issue by franleplant** [ck86/gulp-bower-files#27]
Hi!

When I run

``` javascript
gulpBowerFiles()
  .pipe(gulp.dest("./dist"));
```

I get in `./dist` directory something like this

```
dist
    -- jquery/dist/jquery.js
    -- bootstrap/dist/scripts/bootstrap.js
   ...
```

I had to apply this home made `normalize` function 

Normalize

``` javascript
var normalize = through.obj(function (file, enc, cb){
    //Normalize the paths of Bower files
    file.base = path.dirname( file.path );
    this.push(file);
    cb();
});

gulpBowerFiles()
  .pipe(normalize)
  .pipe(gulp.dest("./dist"));
```

to get this running properly and getting this final result

```
dist
    -- jquery.js
    -- bootstrap.js
   ...
```

As you can see the Vinyl files that you are sending over the stream have an issue with the `file.base` attribute. 

Let `file.path` be

`/path/to/src/file.js`

And `file.base` is currently something like this

`/path/to`

So `file.relative` (or something like `file.path - file.base`) is something like

`src/file.js`

Which leads us the this unwanted behavior.

**Comment by xixixao** [comment]
+1 or at least provide an option in the bower.json to set the output file name (though not sure what to do if the package includes more files). But I think for 99% of cases the `basename` behavior proposed will do.

**Comment by ck86** [comment]
-1

If two or more packages have the same main file(s) defined (e.g. `main: "./index.js"`) it will result in a conflict.
There is a good plugin to "fix" this issue: [gulp-flatten](https://github.com/armed/gulp-flatten).

**Comment by franleplant** [comment]
Hi @ck86! Thanks for that plugin! 

I think that this issue is dead!

Fran

**Comment by xixixao** [comment]
Perfect, thanks for the tip!
