### ISSUE TITLE
gulp.run('grunt-bower'); but no  grunt-bower task defined in gulpfile.js

### ISSUE THREAD

**Issue by tlimpanont** [ck86/gulp-bower-files#28]
in Gruntfile.js I see a task bower_concat which I think it's the task for gulp.run('grunt-bower') ??

**Comment by ck86** [comment]
Sorry if I misunderstand you, but grunt is not gulp?

**Comment by tlimpanont** [comment]
Sorry it wasn't my intention to issues this one here. Never mind!
