### ISSUE TITLE
Fallback on package.json if a dependency doesn't have a bower.json

### ISSUE THREAD

**Issue by nkijak** [ck86/gulp-bower-files#3]
I've noticed some libraries available via bower (e.g. backbone) don't have bower.json but do have package.json and that has a main property pointing to the correct file.

**Comment by nkijak** [comment]
This is something I can add if you think it's appropriate.

**Comment by ck86** [comment]
Why not? I was already working on it, but I'm struggling at breaking a `forEach` loop:

``` javascript
var filenames = ["bower.json", ".bower.json", "package.json"];

filenames.forEach(function(filename){
    bowerJsonPath = path.join(packageJson[dependency].basePath, "/", filename);
    if(fs.existsSync(bowerJsonPath)){
        return false; // will not break the loop?!
    }
    bowerJsonPath = null;
});
```

**Comment by kokujin** [comment]
This would be great if it worked this way, I had problems with a few components and its just defetas the purpose if one has to override the settings for each of them. I could just as well copy the files manually.

**Comment by nkijak** [comment]
Merged in
