### ISSUE TITLE
Ability to concat along with specifying dependencies.

### ISSUE THREAD

**Issue by aamirshah** [ck86/gulp-bower-files#32]
Obviously after getting the main files using bower.json, we will need to compile/concat them  into one single file. This is now its done in [Grunt](https://www.npmjs.org/package/grunt-bower-concat). Looking forward to see same in Gulp.

We can use `gulp.src` and then pipe it to `concat` but the problem is how to specify the order of files automatically

Btw, great work so far.

**Comment by ck86** [comment]
The order is the same as the order specified in your bower.json, but dependencies will be added before the actually package.

**Comment by aamirshah** [comment]
I did not understand `but dependencies will be added before the actually package`. Do you mean to say we need to organize the files in the bower.js in the order we want to have the output. Shouldn't there be an option to add/remove/override this behavior in the plugin ?

**Comment by ck86** [comment]
Why do you want an extra option for that? You can "remove" packages in the `overrides` section if you ignore them:

``` javascript
{
  "overrides": {
    "PACKAGE": {
      "ignore": true
    }
  }
}
```

You can add files to stream, see: #31.

And the part you did not understand is may be better explained with an example:

You have `angularjs` and `bootstrap` install:

``` javascript
{
  "dependencies": {
    "angularjs": "*",
    "bootstrap": "*"
  }
}
```

You will get a stream with the main file(s) of angularjs and then of bootstrap. But bootstrap depends on jQuery. The main file(s) of jQuery will be set before bootstrap.
So you should not have any problems if you concatenate these files.

**Comment by aamirshah** [comment]
Probably, now I've a better understanding of your plugin. Indeed its a great work :+1:  One small question:

For this .json file 

```
{
  "name": "aamir-shah",
  "version": "0.0.0",
  "dependencies": {
    "bootstrap": "*",
    "jquery": "~2.1.1"
  },
  "overrides": {

    "bootstrap": {
      "dependencies": "jquery"
    }
  }
}

```

It does not work, but if I place `jquery` before `bootstrap` everything works fine. In this case how can I tell gulp that `bootstrap` in dependent on `jquery` ?

**Comment by ck86** [comment]
Which version do you have installed? This feature was added in version 0.2.x.

Normally it should place jquery before bootstrap without overriding, because bootstrap depends on jquery. I have tested it successfully, see the output with enabled debugging options:

```
[gulp] PackageCollection add         bootstrap bower_components/bootstrap
[gulp] PackageCollection add         jquery bower_components/jquery
[gulp] Package       select file     jquery bower_components/jquery/dist/jquery.js
[gulp] Package       select file     bootstrap bower_components/bootstrap/dist/css/bootstrap.css
[gulp] Package       select file     bootstrap bower_components/bootstrap/dist/js/bootstrap.js
[gulp] Package       select file     bootstrap bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
[gulp] Package       select file     bootstrap bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
[gulp] Package       select file     bootstrap bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
[gulp] Package       select file     bootstrap bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
```

In case of the package has dependencies, but it was not defined:

``` javascript
{
  "name": "aamir-shah",
  "version": "0.0.0",
  "dependencies": {
    "bootstrap": "*",
    "jquery": "~2.1.1"
  },
  "overrides": {
    "bootstrap": {
      "dependencies": {
        "jquery": "*"
      }
    }
  }
}
```

**Comment by aamirshah** [comment]
Finally I got it right in my [generator](https://github.com/aamirshah/generator-boom). 

@ck86 :+1:
