### ISSUE TITLE
Ignoring files

### ISSUE THREAD

**Issue by mikehaas763** [ck86/gulp-bower-files#33]
So I saw in the readme that there is an overrides section. It's not very clear to me how to use it.

Anyways, here's an issue I'm having. With bower's bootstrap-sass-official, it includes about 8 jquery plugins for bootstrap and they are all included in the packages main key. However, I do not want those (because I'm using angular's ui-bootstrap). Could someone show me an example how I would skip a specific main file(s)?

I wonder if there is a better way to handle this. Having to keep track of files that you want to exclude from an auto included bower package seems worse than keeping track of files you want to include from a bower package.

**Comment by ck86** [comment]
There is no options to exclude files yet, but you can override the main property:

``` javascript
{
  "overrides": {
    "bootstrap-sass-official": {
      "main": [
        // files you want to include
      ]
    }
  }
}
```

**Comment by ck86** [comment]
Is it working for you?

**Comment by mikehaas763** [comment]
I decided not to use this. I already have a buildconfig file that I use for all kinds of options especially for stuff I use in my gulp tasks. So it makes more sense for me to keep my list of references in that file.

Thanks.

**Comment by adewinter** [comment]
For anyone who stumbles across this:

To ignore an entire package, this works:

```
{
  "overrides": {
    "bootstrap-sass-official": {  //name of package you want to ignore
      "main": [
        // keep this blank to skip the entire package
      ]
    }
  }
}
```
