### ISSUE TITLE
Files not found are silently ignored

### ISSUE THREAD

**Issue by stephane** [ck86/gulp-bower-files#35]
Why the files not found are silently ignored (not existing file in main list)?

**Comment by ck86** [comment]
Which files?

**Comment by stephane** [comment]
If a main key in bower.json file contains a non existing file, no errors are raised when the task runs.
For example with:

``` javascript
"overrides": {
    "jquery": {
      "main": ["dist/foobar-doesnt-exist.min.js"]
    },
```
