### ISSUE TITLE
Destination dir and renaming

### ISSUE THREAD

**Issue by stephane** [ck86/gulp-bower-files#36]
I can't find a way to rename files copied from bower directory.

I would be nice if I could do something like that to rename "dist/jquery.min.js" to "jquery.min.js":

``` javascript
"overrides": {
    "jquery": {
      "main": {"dist/jquery.min.js": "jquery.min.js"}
    },
```

**Comment by ybouhjira** [comment]
@stephane I had this problem too before I used `gulp-rename`

``` js
bower()
    .pipe(rename({dirname: ''}))
    .pipe(gulp.dest('client/src/lib'));
```

It puts all the `.js` files directly in `client/src/lib`

**Comment by ck86** [comment]
Alternatively you can use [gulp-flatten](https://github.com/armed/gulp-flatten).

**Comment by stephane** [comment]
OK it's certainly not in the scope of gulp-bower-files to change the path.
