### ISSUE TITLE
skips dependencies that are not listed in bower.json

### ISSUE THREAD

**Issue by ybouhjira** [ck86/gulp-bower-files#38]
I have `angular-google-maps` in my bower.json. This library depends on `underscore` which is also located in `bower_components` directory, but it's not found by `gulp-bower-files`

**Comment by ck86** [comment]
Which version do you have installed?

**Comment by ybouhjira** [comment]
0.2.2

**Comment by ck86** [comment]
I have installed `angular-google-maps` in a new clean project. It does not depend on `underscore`, but on `angular` and `lodash` and both was found by this plugin.

**Comment by ybouhjira** [comment]
I am using `angular-google-maps 1.0.18` (old version, that I shall update) which depens on `underscore` I tried a clean project and everything worked nicely. here is the project which has the problem : https://github.com/ybouhjira/gps-tracking

**Comment by ck86** [comment]
I have added an pull request to your project which solves the problem.
