### ISSUE TITLE
Separate css from js deps

### ISSUE THREAD

**Issue by soyuka** [ck86/gulp-bower-files#42]
Hey there, nice plugin! I love the `bower.json` deps override/ignore it's a nice idea!

It would be nice having a way to separate css from js files.

What about adding an option to this?

```
gulp.task('bower', function() {
  bower({jsonly: true})
        .pipe(concat('vendor.js'))
        .pipe(uglify())
                .pipe(gulp.dest('./dist'))
})
```

**Comment by ck86** [comment]
Thanks!

There is another nice plugin called `gulp-filter` which does exactly what you need. ;-)

**Comment by soyuka** [comment]
Yes I thought about using it right after writing the issue ^^ (long day...)
